import type { Metadata } from "next";

import {Inter} from "next/font/google"
import "./globals.css";
import Navbar from "./components/navbar";
import Page from "./Component-01/page"
import Two from "./component-02/page"
import Three from "./component-03/page"
import Four from "./component-04/page";
import Five from "./component-05/page";
import Six from "./component-06/page";
import Seven from "./component-07/page";

const inter = Inter({subsets : ["latin"]});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Page />
        <Two />
        <Three />
        <Four />
        <Five />
        <Six />
        <Seven />
        {children}
      </body>
    </html>
  );
}
